export const SAVE_ACCESS_TOKEN = "SAVE_ACCESS_TOKEN";
export const SAVE_REFRESH_TOKEN = "SAVE_RESTORE_TOKEN";
export const CLEAR_STORE = "CLEAR_STORE";
export const ADD_RESTORE_DATA = "ADD_RESTORE_DATA";
