before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - apt-get install sshpass
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_staging:
  type: deploy
  environment:
    name: staging
    url: http://ls-admin.work-jetup.site/
  script:
    - sshpass -p $SSH_PASSWORD ssh root@185.69.154.136 "cd $SSH_PROJECT_PATH &&
        git reset --hard && 
        git pull origin master && 
        npm run build
      "
  only:
    - master
