export const SAVE_REQUEST_STATISTIC = 'SAVE_REQUEST_STATISTIC'
export const SAVE_AMOUNT_ACTIVE_USER = 'SAVE_AMOUNT_ACTIVE_USER'
export const SAVE_AMOUNT_DOCUMENT_IN_REVIEW = 'SAVE_AMOUNT_DOCUMENT_IN_REVIEW'
