export const SIGN_IN = '/sign-in'
export const SIGN_OUT = '/sign-out'
export const FORGOT_PASSWORD = '/forgot-password'
export const DOCUMENTS = '/documents'
export const USERS = '/users'
export const PROFILE = '/profile'
